apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: backend
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        track: stable
    spec:
      containers:
        - name: backend
          image: ghcr.io/cvetacapova/dummybe:main
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
